// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "2557d1fa-581b-4637-87a4-3aaae879a955";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onMaxTempChange();
void onFanOnChange();
void onOverrideFanControlChange();

float max_temp;
float temperature;
bool fan_on;
bool override_fan_control;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(max_temp, READWRITE, ON_CHANGE, onMaxTempChange);
  ArduinoCloud.addProperty(temperature, READ, 5 * SECONDS, NULL);
  ArduinoCloud.addProperty(fan_on, READWRITE, ON_CHANGE, onFanOnChange);
  ArduinoCloud.addProperty(override_fan_control, READWRITE, ON_CHANGE, onOverrideFanControlChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
